# Generated by Django 3.2.5 on 2021-09-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employer', '0002_myuser_is_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('graduation', models.CharField(max_length=120)),
                ('post_graduation', models.CharField(blank=True, max_length=120, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('certifications', models.CharField(blank=True, max_length=150, null=True)),
                ('resume', models.FileField(upload_to='files')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('Under_review', 'Under_review'), ('Interview_scheduled', 'Interview_scheduled')], default='applied', max_length=75)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.jobpost')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobseeker.jobseekerprofile')),
            ],
        ),
    ]
