# Generated by Django 3.2.5 on 2021-09-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='euser',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
