# Generated by Django 3.2.5 on 2021-09-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0006_jobpost_status'),
        ('Jobseeker', '0002_jobapplymodel_euser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='applied_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employer.jobpost'),
        ),
    ]
