# Generated by Django 3.2.5 on 2021-08-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=25)),
                ('field', models.CharField(max_length=40)),
                ('company_size', models.IntegerField()),
                ('headquarters', models.CharField(max_length=60)),
                ('industry_type', models.CharField(max_length=30)),
                ('specialities', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Employer', 'Employer'), ('Employee', 'Employee'), ('options', 'options')], default='centerhead', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=40)),
                ('min_experience', models.CharField(max_length=10)),
                ('max_experience', models.CharField(max_length=10)),
                ('vacancies', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=40)),
                ('salary', models.CharField(max_length=40)),
                ('job_discription', models.CharField(max_length=100)),
                ('candidate_profile', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.employerprofile')),
            ],
        ),
    ]
