# Generated by Django 3.2.5 on 2021-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_myuser_is_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(max_length=300),
        ),
    ]
