# Generated by Django 3.2.5 on 2021-09-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_alter_employerprofile_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='myuser',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
