# Generated by Django 3.2.5 on 2021-09-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0004_jobpost_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
