# Generated by Django 3.2.5 on 2021-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_employerprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled')], default='created', max_length=75),
        ),
    ]
